<a href="https://colab.research.google.com/github/paveena703/structure-array/blob/main/structed_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print('Creating Simple Array')
trainname = ['Rock Fort SF Express', 'Uzhavan Express', 'TEJAS','EXPRESS', 'Pothigai SF Express']
trainnumber = [12654, 16866, 22672, 12662]

Creating Simple Array


In [ ]:
route =['Trichy to Chennai','Thanjavur to Chennai','Madurai to Chennai', 'Sengottai to Chennai']
distance = [337.0, 351, 497.0, 670.0]
print('Train Name :',trainname,'\n Train Number:',trainnumber,'\n Train Route :',route,'\n Distance:',distance)

Train Name : ['Rock Fort SF Express', 'Uzhavan Express', 'TEJASEXPRESS', 'Pothigai SF Express'] 
 Train Number: [12654, 16866, 22672, 12662] 
 Train Route : ['Trichy to Chennai', 'Thanjavur to Chennai', 'Madurai to Chennai', 'Sengottai to Chennai'] 
 Distance: [337.0, 351, 497.0, 670.0]


In [ ]:
print('Creating Structured Array')
data = np.zeros(4, dtype={'names':('trainname', 'trainnumber',
'route','distance'),
'formats':('U10', 'i4', 'U10','f8')})

Creating Structured Array


In [ ]:
print('Train Database Data Type',data.dtype)
data['trainname'] = trainname
data['trainnumber'] = trainnumber
data['route'] = route
data['distance']=distance

Train Database Data Type [('trainname', '<U10'), ('trainnumber', '<i4'), ('route', '<U10'), ('distance', '<f8')]


In [ ]:
print('Prinitng Data',data)
print('Working in Structured Arrays')
print('Train Names :',data['trainname'])
print('Printing First Data :',data[0])

Prinitng Data [('Rock Fort ', 12654, 'Trichy to ', 337.)
 ('Uzhavan Ex', 16866, 'Thanjavur ', 351.)
 ('TEJASEXPRE', 22672, 'Madurai to', 497.)
 ('Pothigai S', 12662, 'Sengottai ', 670.)]
Working in Structured Arrays
Train Names : ['Rock Fort ' 'Uzhavan Ex' 'TEJASEXPRE' 'Pothigai S']
Printing First Data : ('Rock Fort ', 12654, 'Trichy to ', 337.0)


In [ ]:
print('Printing Train List Less than 400 KM Distance:\n',data[data['distance'] < 400])
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

Printing Train List Less than 400 KM Distance:
 [('Rock Fort ', 12654, 'Trichy to ', 337.)
 ('Uzhavan Ex', 16866, 'Thanjavur ', 351.)]
(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
